version: '3.8'

services:
  terboro:
    image: ghcr.io/robertorincos/terboro:latest
    container_name: terboro_site
    ports:
      - "82:80"
    restart: always
    environment:
      - NODE_ENV=production