version: '3.8'

services:
  terboro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terboro_site
    ports:
      - "82:82"
    restart: always
    environment:
      - NODE_ENV=production